const CoinsActionTypes = {
  LOAD_COINS_START: 'LOAD_COINS_START',
  LOAD_COINS_SUCCESS: 'LOAD_COINS_SUCCESS',
  LOAD_COINS_FAIL: 'LOAD_COINS_FAILED',
  LOAD_NEW_COINS_PAGE_START: 'LOAD_NEW_COINS_PAGE_START',
  LOAD_NEW_COINS_PAGE_SUCCESS: 'LOAD_NEW_COINS_PAGE_SUCCESS',
  LOAD_NEW_COINS_PAGE_FAIL: 'LOAD_NEW_COINS_PAGE_FAIL',
  LOAD_COIN_DETAIL_START: 'LOAD_COIN_DETAIL_START',
  LOAD_COIN_DETAIL_SUCCESS: 'LOAD_COIN_DETAIL_SUCCESS',
  LOAD_COIN_DETAIL_FAIL: 'LOAD_COIN_DETAIL_FAIL',
  CONVERT_VALUE_START: 'CONVERT_VALUE_START',
  CONVERT_VALUE_SUCCESS: 'CONVERT_VALUE_SUCCESS',
  CONVERT_VALUE_FAIL: 'CONVERT_VALUE_FAIL',
};

export default CoinsActionTypes;
